"""
apply_fix.py — Run this once to fix data_loader.py in place.
    python apply_fix.py
"""
import pathlib

content = (
    '"""\n'
    'data_loader.py - Load real CSVs or fall back to synthetic data\n'
    '==============================================================\n'
    '"""\n'
    '\n'
    'import pandas as pd\n'
    'from pathlib import Path\n'
    'from config import DATA_DIR, FILES, USE_SYNTHETIC_IF_MISSING\n'
    '\n'
    '\n'
    'def _parse_dates(df):\n'
    '    """Auto-convert columns that look like dates."""\n'
    '    date_hints = [\n'
    '        "date", "diag_date", "staging_date", "metastatic_date",\n'
    '        "start_date", "end_date", "last_activity", "test_date",\n'
    '        "result_date", "specimen_collection_date", "event_date",\n'
    '        "change_date", "visit_date", "lot_end_date",\n'
    '        "drug_exposure_start_date", "drug_exposure_end_date",\n'
    '        "cond_st_date", "cond_end_date", "date_event", "date_end",\n'
    '        "disease_date", "last_curation_date", "remapped_date",\n'
    '        "change_date_end",\n'
    '    ]\n'
    '    for col in df.columns:\n'
    '        if col.lower() in date_hints or col.lower().endswith("_date"):\n'
    '            try:\n'
    '                df[col] = pd.to_datetime(df[col], errors="coerce")\n'
    '            except Exception:\n'
    '                pass\n'
    '    return df\n'
    '\n'
    '\n'
    'def load_tables(table_names=None):\n'
    '    """\n'
    '    Load requested tables from CSV.\n'
    '    Falls back to synthetic data if USE_SYNTHETIC_IF_MISSING is True.\n'
    '    """\n'
    '    if table_names is None:\n'
    '        table_names = list(FILES.keys())\n'
    '\n'
    '    data_path = Path(DATA_DIR)\n'
    '    real_data_available = data_path.exists() and any(\n'
    '        (data_path / FILES[t]).exists() for t in table_names if t in FILES\n'
    '    )\n'
    '\n'
    '    if real_data_available:\n'
    '        print(f"[data_loader] Loading real data from {data_path}")\n'
    '        tables = {}\n'
    '        for name in table_names:\n'
    '            fpath = data_path / FILES[name]\n'
    '            if fpath.exists():\n'
    '                try:\n'
    '                    df = pd.read_csv(fpath, low_memory=False, encoding="utf-8")\n'
    '                except UnicodeDecodeError:\n'
    '                    df = pd.read_csv(fpath, low_memory=False, encoding="latin-1")\n'
    '                df = _parse_dates(df)\n'
    '                tables[name] = df\n'
    '                n = len(df)\n'
    '                print(f"  v {name:20s}  {n:>7,} rows")\n'
    '            else:\n'
    '                print(f"  x {name:20s}  FILE NOT FOUND: {fpath.name}")\n'
    '        return tables\n'
    '\n'
    '    elif USE_SYNTHETIC_IF_MISSING:\n'
    '        print("[data_loader] Real CSVs not found - generating synthetic data")\n'
    '        from synthetic_data import generate_all_synthetic_tables\n'
    '        tables = generate_all_synthetic_tables()\n'
    '        return {k: v for k, v in tables.items() if k in table_names}\n'
    '\n'
    '    else:\n'
    '        raise FileNotFoundError(\n'
    '            f"Data directory {data_path} not found and '\
            'USE_SYNTHETIC_IF_MISSING=False. "\n'
    '            f"Set PEMBRO_DATA_DIR env variable or place CSVs in {data_path}"\n'
    '        )\n'
)

out = pathlib.Path(__file__).parent / "data_loader.py"
out.write_text(content, encoding="utf-8")
print(f"Written: {out}")
